name = "backend"
compatibility_date = "2023-12-01"

#this is the connection pool url 

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOTFhOTJjYmEtMmZiOS00Y2E0LTljMmUtZTZkNTE1ZmI1ODE5IiwidGVuYW50X2lkIjoiNjk3Y2QyYTczMTQ4Yjg4MTFhZTNmZjQ1MzJiMDlmYTIzOWIyNDE2ODc0MTFhN2FlYzNjYTEyOTg4MzlmZTI0MCIsImludGVybmFsX3NlY3JldCI6ImI5Mjk5YjFkLWJiOTctNGU5NC05NjZjLTFiNjg0YjYwM2UxMCJ9.aUKXlYDfJctccgstanON__O1bBRspZCaHr5twBso9U4"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"